### ISSUE TITLE
Snatched plugin does not execute

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/watcherplugins#3]
I'm writing a Pushover plugin for my snatches. It seems as if the loop that would trigger the plugin is not executing - I've put a logging statement on line 188 of snatcher.py and it never shows up in the log.

Any thoughts?

**Comment by nosmokingbandit** [comment]
Without seeing your log I can't know what is going on.

Plugins are being executed for me, so something must be failing before that block.

**Comment by barbequesauce** [comment]
Turned out to be a misconfigured Deluge instance... sorry.
